routes/web.php
<?php
//Controller
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Frontend\SearchController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\Frontend\JobController;
use App\Http\Controllers\GeoLocationController;
use App\Http\Controllers\AuthCompany\AuthCompanyController;
//API
use App\Http\Controllers\API\AuthController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('get-address-from-ip',[GeoLocationController::class, 'index']);

Route::get('/', [HomeController::class, 'index'])->name('index');
Route::get('/reset_password', [HomeController::class, 'resetPassword'] )->name('password.reset');
Route::get('/privacy_policy', [HomeController::class, 'privacyPolicy'] )->name('privacy.policy');
Route::post('/password_update', [HomeController::class, 'passwordUpdate'] )->name('password.update');

Route::get('/search', [SearchController::class, 'index'])->name('search');
Route::get('/job/{id}', [JobController::class, 'index'])->name('job');
Route::get('/login', [AuthCompanyController::class, 'index'] )->name('login');
Route::post('/login', [AuthCompanyController::class, 'login'])->name('login.auth');
Route::post('/logout', [AuthCompanyController::class, 'logout'])->name('logout.auth');

Route::get('/signup', [AuthCompanyController::class, 'viewSignup'] )->name('signup.view');
Route::post('/signup', [AuthCompanyController::class, 'signup'] )->name('signup.auth');

Route::prefix('dashboard')->as('company.')->group(function() {
    Route::get('/',  [DashboardController::class, 'index'] )->name('home');
    Route::get('/applicant/{id}',  [DashboardController::class, 'applicant'] )->name('applicant');
    Route::get('/applicant/selected/{id}',  [DashboardController::class, 'applicantSelected'] )->name('applicant.selected');
    Route::get('/applicant/interviewed/{id}',  [DashboardController::class, 'applicantInterviewed'] )->name('applicant.interviewed');
    Route::get('/applicant/notsuitable/{id}',  [DashboardController::class, 'applicantNotsuitable'] )->name('applicant.notsuitable');
    Route::get('/vacancies/create',  [DashboardController::class, 'vacanciesForm'] )->name('vacancies.form.create');
    Route::get('/companies',  [DashboardController::class, 'companiesForm'] )->name('companies.form.create');
    Route::post('/companies/update',  [DashboardController::class, 'companies'] )->name('companies.update');
    Route::get('/vacancies/update/{id}',  [DashboardController::class, 'vacanciesForm'] )->name('vacancies.form.update');
    Route::post('/vacancies', [DashboardController::class, 'vacancies'])->name('vacancies.create');
    Route::put('/vacancies', [DashboardController::class, 'vacancies'])->name('vacancies.update');

    Route::post('/applicant/update', [DashboardController::class, 'applicantUpdate'])->name('applicant.update');

 });

Route::get('/firebase_auth', function () {
    return view('firebase_auth');
});

Route::get('/firebase_auth_2', function () {
    return view('firebase_auth_2');
});


//For React Only
// Route::get( '/{path?}', function(){
//     return view('index');
// })->where('path', '.*');Auth::routes();

Route::get('/home', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;

/** Carbon */

use Illuminate\Support\Carbon;

/** Models */

use App\Models\Job\Jobs;
use App\Models\Categories;
use App\Models\Companies;
use App\Models\Job\JobsCategories;
use App\Models\Job\JobsSpecialization;
use App\Models\Job\JobsRegions;
use App\Models\Job\JobsEducations;
use App\Models\Job\JobsIndustries;
use App\Models\Applicant\Apply;
use App\Models\Regions;
use App\Models\Location\Regency;
use App\Models\Master\EducationMaster;
use App\Models\Master\IndustriesMaster;
use App\Models\Master\SpecializationSubMaster;

/** Auth */

use Illuminate\Support\Facades\Auth;

/** Javascript */

use Laracasts\Utilities\JavaScript\JavaScriptFacade;

/** Meta Tools */

use Artesaos\SEOTools\Facades\SEOMeta;
use Artesaos\SEOTools\Facades\OpenGraph;
use Artesaos\SEOTools\Facades\TwitterCard;
use Artesaos\SEOTools\Facades\JsonLd;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

use Illuminate\Support\Facades\Storage;

class DashboardController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth:company')->except('logout');
    }

    public function index(Request $request)
    {
        $title = "Dashboard";
        SEOMeta::setTitle($title);
        JsonLd::setTitle($title);

        $job = Jobs::with(['applied'])->paginate(3);
        $now = Carbon::now()->format("Y-m-d");
        //dd($job[0]->applied->where("apply_status",0)->count());
        return view('backend/index')
            ->with('now', $now)
            ->with('job', $job);
    }

    public function vacanciesForm(Request $request)
    {
        $job = null;

        $form = true; // Create

        if ($request->id) {
            $job = Jobs::with(['specializations', 'industries', 'categories', 'regions'])->findOrFail($request->id);
            $form = false; // Update
        }

        $locations = Regency::get();
        $categories = Categories::get();
        $specialization = SpecializationSubMaster::get();
        $industries = IndustriesMaster::get();
        $educations = EducationMaster::get();

        // dd($job->industries()->get(['industries_id as id', 'industries_name as text'])->toArray());
        // dd($job->educations()->get(['educations.education_id as id', 'educations.education_name as text'])->toArray());
        if ($request->id) {
            JavaScriptFacade::put([
                'specialization_sub_id' => $job->specializations()->get(['specialization_sub_id as id', 'specialization_sub_name as text'])->toArray(),
                'industries_id' => $job->industries()->get(['industries.industries_id as id', 'industries.industries_name as text'])->toArray(),
                'education_id' => $job->educations()->get(['educations.education_id as id', 'educations.education_name as text'])->toArray(),
                'categories_id' => $job->categories()->get(['categories.categories_id as id', 'categories.categories_name as text'])->toArray(),
                'region_id' => $job->regions()->get(['id as id', 'name as text'])->toArray(),
            ]);
        }

        return view('backend/vacancies')
            ->with('job', $job)
            ->with('form', $form)
            ->with('locations', $locations)
            ->with('categories', $categories)
            ->with('educations', $educations)
            ->with('specialization', $specialization)
            ->with('industries', $industries);
    }

    public function companiesForm(Request $request)
    {
        $job = null;
        $form = false; // Update
        $company = Companies::findOrFail($request->user()->company_id);
        $industries = IndustriesMaster::get();
        $dataindustries = IndustriesMaster::findOrFail($company->company_industry);
        $arrindustries = [['id' => $dataindustries->industries_id, "text" => $dataindustries->industries_name]];
        // dd($arrindustries);
        JavaScriptFacade::put([
            'industries_id' => $arrindustries,
        ]);

        return view('backend/companies')
            ->with('job', $job)
            ->with('form', $form)
            ->with('company', $company)
            ->with('industries', $industries);
    }

    public function companies(Request $request)
    {
        // dd($request->company_image);
        // $validatedData = $request->validate([
        //     'company_image' => ['max:128'],
        // ]);

        // dd($validatedData);

        try {
            DB::beginTransaction();
            $now = Carbon::now()->format("Y-m-d");
            $expired = Carbon::now()->addWeeks(2)->format("Y-m-d");
            $companies = companies::findOrFail($request->user()->company_id);
            $img_title = md5(microtime());
            // Storage::disk('public')->put("images/companies/" . $img_title . '.jpg', $request->file('company_image'), 'public');
            if ($request->file('company_image')) {
                $request->file('company_image')->storeAs('public/images/companies/', $img_title . ".jpg");
            }
            $companies->company_name = $request->company_name;
            $companies->company_address = $request->company_address;
            $companies->company_mail = $request->company_mail;
            $companies->company_phone = $request->company_phone;
            $companies->company_industry = $request->company_industry;
            $companies->company_overview = $request->company_overview;
            if ($request->file('company_image')) {
                $companies->company_image = "app/images/companies/" . $img_title . ".jpg";
            }
            $companies->company_min_employee = $request->company_employee;
            $companies->company_max_employee = $request->company_employee;
            $companies->save();
            DB::commit();
            return redirect("dashboard/companies")->with('message', 'Data Berhasil diupdate');
        } catch (\Exception $e) {
            DB::rollBack();
            dd($e);
            Log::debug($e);
        }
    }

    public function applicantUpdate(Request $request)
    {
        $apply = Apply::where("user_id", $request->user_id)->where("job_id", $request->job_id)->update(['apply_status' => $request->apply_status]);
        return json_encode(($apply));
    }

    public function updateVacancies(Request $request)
    {
        $locations = Regency::get();
        $categories = Categories::get();
        $specialization = SpecializationSubMaster::get();
        $industries = IndustriesMaster::get();
        return view('backend/vacancies')
            ->with('locations', $locations)
            ->with('categories', $categories)
            ->with('specialization', $specialization)
            ->with('industries', $industries);
    }

    public function vacancies(Request $request)
    {
        $user = $request->user();
        try {
            DB::beginTransaction();
            $now = Carbon::now()->format("Y-m-d");
            $expired = Carbon::now()->addWeeks(2)->format("Y-m-d");
            if ($request->job_id) {
                $job = Jobs::findOrFail($request->job_id);
            } else {
                $job = new Jobs();
            }
            $job->job_title = $request->job_title;
            $job->company_id = $user->company_id;
            $job->job_posted = $now;
            $job->job_expired = $expired;
            $job->job_description = $request->job_description;
            $job->job_employment_type = $request->job_employment_type;
            $job->job_status = 1;
            $job->min_salary = $request->min_salary;
            $job->max_salary = $request->max_salary;
            $job->save();

            JobsCategories::where('job_id', $job->job_id)->delete();
            $sequence = 0;
            foreach ($request->job_categories as $key => $value) {
                $categories = new JobsCategories();
                $categories->job_id = $job->job_id;
                $categories->job_categories_seq = $sequence++;
                $categories->categories_id = $value;
                $categories->save();
            }

            JobsEducations::where('job_id', $job->job_id)->delete();
            $sequence = 0;
            foreach ($request->job_educations as $key => $value) {
                $education = new JobsEducations();
                $education->job_id = $job->job_id;
                $education->job_educations_seq = $sequence++;
                $education->education_id = $value;
                $education->save();
            }

            JobsIndustries::where('job_id', $job->job_id)->delete();
            $sequence = 0;
            foreach ($request->job_industries as $key => $value) {
                $industries = new JobsIndustries();
                $industries->job_id = $job->job_id;
                $industries->job_industries_seq = $sequence++;
                $industries->industries_id = $value;
                $industries->save();
            }

            JobsSpecialization::where('job_id', $job->job_id)->delete();
            $sequence = 0;
            foreach ($request->job_specialization as $key => $value) {
                $specialization = new JobsSpecialization();
                $specialization->job_id = $job->job_id;
                $specialization->job_specialization_seq = $sequence++;
                $specialization->specialization_sub_id = $value;
                $specialization->save();
            }

            JobsRegions::where('job_id', $job->job_id)->delete();
            foreach ($request->job_locations as $key => $value) {
                $region = new JobsRegions();
                $region->job_id = $job->job_id;
                $region->region_id = $value;
                $region->save();
            }
            DB::commit();
            return redirect("dashboard")->with('message', 'Lowongan berhasil dibuat');
        } catch (\Exception $e) {

resources/views/backend/index.blade.php
@extends('layouts.backend')
@section('content')
<div class="w-full mt-4 px-3">
    @if(session()->has('message'))
    <div class="flex justify-center items-center m-1 font-medium py-1 px-2 bg-white rounded-md text-green-700 bg-green-100 border border-green-300 ">
        <div slot="avatar">
            <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check-circle w-5 h-5 mx-2">
                <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
                <polyline points="22 4 12 14.01 9 11.01"></polyline>
            </svg>
        </div>
        <div class="text-xl font-normal  max-w-full flex-initial">
            {{ session()->get('message') }}
        </div>
        <div class="flex flex-auto flex-row-reverse">
            <div>
                <!-- <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x cursor-pointer hover:text-green-400 rounded-full w-5 h-5 ml-2">
                            <line x1="18" y1="6" x2="6" y2="18"></line>
                            <line x1="6" y1="6" x2="18" y2="18"></line>
                        </svg> -->
            </div>
        </div>
    </div>
    @endif
    @foreach ($job as $item)
    <div class="w-full flex justify-between p-5 rounded-sm shadow-md my-5 bg-white">
        <div class="md:w:5/12 lg:w-1/2 w-full">
            <div class="text-xl text-green-500 font-semibold">{{ $item->job_title }}</div>
            <div class="mt-2 text-sm text-gray-400">{{ ( $now > $item->job_posted->addDays(20)->format("Y-m-d") ) ? "Sudah Berakhir" : "Berakhir Pada ".$item->job_posted->addDays(20)->format("Y-m-d") }}</div>
            <div class="flex mt-2">
                <!-- <a href="{{ route('company.applicant',$item->job_id) }}" class="text-sm text-blue-500 mx-3 ml-0">lihat</a> -->
                <a href="{{ route('company.vacancies.form.update',$item->job_id ) }}" class="text-sm text-blue-500">ubah</a>
                <a href="#" class="text-sm text-blue-500 mx-3">hapus</a>
            </div>
            <div class="w-full flex mt-2 md:hidden">
                <div class="w-1/2 rounded-sm shadow-sm border-gray-100 m-1 p-1 text-center">
                    <a href="{{ route('company.applicant',$item->job_id) }}" class="text-lg text-center text-blue-500">{{ $item->applied->where("apply_status",0)->count() }}</br> <span class="text-sm">menunggu</span></a>
                </div>
                <div class="w-1/2 rounded-sm shadow-sm border-gray-100 m-1 p-1 text-center">
                    <a href="{{ route('company.applicant.selected',$item->job_id) }}" class="text-lg text-center text-blue-500">{{ $item->applied->where("apply_status",2)->count() }}</br> <span class="text-sm">terpilih</span></a>
                </div>
            </div>
            <div class="w-full flex mt-2 md:hidden">
                <div class="w-1/2 rounded-sm shadow-sm border-gray-100 m-1 p-1 text-center">
                    <a href="{{ route('company.applicant.interviewed',$item->job_id) }}" class="text-lg text-center text-blue-500">{{ $item->applied->where("apply_status",3)->count() }}</br> <span class="text-sm">wawancara</span></a>
                </div>
                <div class="w-1/2 rounded-sm shadow-sm border-gray-100 m-1 p-1 text-center">
                    <a href="{{ route('company.applicant.notsuitable',$item->job_id) }}" class="text-lg text-center text-blue-500">{{ $item->applied->where("apply_status",3)->count() }}</br> <span class="text-sm">tidak sesuai</span></a>
                </div>
            </div>
        </div>
        <div class="hidden md:block md:w:7/12 lg:w-1/2">
            <div class="flex justify-end">
                <a href="{{ route('company.applicant',$item->job_id) }}" class="flex flex-col w-1/4 items-center px-3 py-1 rounded-sm shadow mx-3">
                    <div class="text-5xl text-blue-500">{{ $item->applied->where("apply_status",0)->count() }}</div>
                    <div class="mt-2 text-center text-blue-500">Belum diproses</div>
                </a>
                <a href="{{ route('company.applicant.selected',$item->job_id) }}" class="flex flex-col w-1/4 items-center px-3 py-1 rounded-sm shadow mx-3">
                    <div class="text-5xl text-blue-500">{{ $item->applied->where("apply_status",2)->count() }}</div>
                    <div class="mt-2 text-center text-blue-500">Terpilih</div>
                </a>
                <a href="{{ route('company.applicant.interviewed',$item->job_id) }}" class="flex flex-col w-1/4 items-center px-3 py-1 rounded-sm shadow mx-3">
                    <div class="text-5xl text-blue-500">{{ $item->applied->where("apply_status",3)->count() }}</div>
                    <div class="mt-2 text-center text-blue-500">Wawancara</div>
                </a>
                <a href="{{ route('company.applicant.notsuitable',$item->job_id) }}" class="flex flex-col w-1/4 items-center px-3 py-1 rounded-sm shadow mx-3">
                    <div class="text-5xl text-blue-500">{{ $item->applied->where("apply_status",4)->count() }}</div>
                    <div class="mt-2 text-center text-blue-500">Tidak Sesuai</div>
                </a>
            </div>
        </div>
    </div>
    @endforeach
    <div class="lg:container mx-auto flex justify-center my-10">
        {!! $job->onEachSide(2)->links() !!}
    </div>
</div>
@endsection
@section('scripts')
@endsection

resources/views/backend/vacancies.blade.php
@extends('layouts.backend')
@section('content')
<!-- <div class="flex justify-center h-14 w-full -bottom-7"> -->
    <div class="w-11/12 md:w-3/5 mb-5 flex flex-wrap justify-center p-1 rounded-md bg-whiteborder-b border-l border-grey-light lg:border-l-0 lg:border-t lg:border-grey-light bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal col-span-full shadow rounded-sm">
        <form method="POST" action="{{ 
            $form ? route('company.vacancies.create') : route('company.vacancies.update') }}" class="w-full">
            @csrf
            <div class="flex flex-wrap -mx-3 mb-6 mt-5">
                @if($job)
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="job_id" value="{{ $job->job_id }}">
                @endif
                <div class="w-full px-3 mb-6">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-job-title">
                        Judul
                    </label>
                    <input class="appearance-none block w-full text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="job-title" name="job_title" type="text" placeholder="IT Surveyor" value="{{ $job ? $job->job_title : '' }}">
                </div>
                <div class="w-full px-3 mb-6">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-job-title">
                        Deskripsi
                    </label>
                    <textarea id="test" name="job_description">
                    {{ $job ? $job->job_description : '' }}
                    </textarea>
                </div>
                <div class="w-full md:w-1/2 mb-6 px-3">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-min-salary">
                        Gaji Minimal
                    </label>
                    <input class="appearance-none block w-full text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-min-salary" name="min_salary" type="number" placeholder="5000000" value="{{ $job ? $job->min_salary : '' }}">
                </div>
                <div class="w-full md:w-1/2 mb-6 px-3">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-max-salary">
                        Gaji Maksimal
                    </label>
                    <input class="appearance-none block w-full text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-max-salary" name="max_salary" type="number" placeholder="5000000" value="{{ $job ? $job->max_salary : '' }}">
                </div>
                <div class="w-full mb-6 px-3">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">
                        Tipe Pekerjaan
                    </label>
                    <select id="job_employment_type" name="job_employment_type" class="w-full py-3 px-4">
                        <option value="1">Full Time</option>
                        <option value="2">Part Time</option>
                    </select>
                </div>
                <div class="w-full mb-6 px-3">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">
                        Kategori
                    </label>
                    <select id="job_categories" name="job_categories[]" class="w-full py-3 px-4" multiple="multiple">
                        @foreach($categories as $item)
                        <option value="{{ $item->categories_id }}">{{ $item->categories_name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="w-full mb-6 px-3">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">
                        Pendidikan
                    </label>
                    <select id="job_educations" name="job_educations[]" class="w-full py-3 px-4" multiple="multiple">
                        @foreach($educations as $item)
                        <option value="{{ $item->education_id }}">{{ $item->education_name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="w-full mb-6 px-3">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">
                        industri
                    </label>
                    <select id="job_industries" name="job_industries[]" class="w-full py-3 px-4" multiple="multiple">
                    </select>
                </div>
                <div class="w-full mb-6 px-3">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" multiple="multiple">
                        Lokasi
                    </label>
                    <div class="form-group">
                        <select id="job_locations" name="job_locations[]" class="w-full py-3 px-4" multiple="multiple">
                        </select>
                    </div>
                </div>
                <div class="w-full mb-6 px-3">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">
                        Spesialisasi
                    </label>
                    <div class="form-group">
                        <select id="job_specialization" name="job_specialization[]" class="w-full py-3 px-4" multiple="multiple">
                        </select>
                    </div>
                </div>
            </div>
            <div class="inline-block mr-2 mt-2">
                <button type="submit" class="focus:outline-none text-white text-sm py-2.5 px-5 rounded-md bg-blue-500 hover:bg-blue-600 hover:shadow-lg">Submit</button>
            </div>
        </form>
    </div>
<!-- </div> -->
@endsection
@section('scripts')
<script>
    $(document).ready(function() {
        ClassicEditor
            .create(document.querySelector('#test'), {
                toolbar: ['bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote'],
            })
            .catch(error => {
                console.error(error);
            });

        $('#job_categories').select2({
            dropdownPosition: 'below',
            placeholder: "Kategori Pekerjaan"
        });

        $('#job_educations').select2({
            dropdownPosition: 'below',
            placeholder: "Kategori Pendidikan"
        });

        $('#job_employment_type').select2({
            dropdownPosition: 'below',
            placeholder: "Tipe Pekerjaan"
        });

        $('#job_industries').select2({
            placeholder: "Choose tags...",
            minimumInputLength: 2,
            debug: true,
            ajax: {
                url: "{{ route('select_industries') }}",
                dataType: 'json',
                data: function(params) {
                    return {
                        term: params.term || '',
                        page: params.page || 1
                    }
                },
                // processResults: function(data, params) {
                //     params.page = params.page || 1;
                //     return {
                //         results: data.results,
                //         pagination: {
                //             more: (params.page * 10) < data.count_filtered
                //         }
                //     };
                // },
                cache: true,
            }
        });

        $('#job_specialization').select2({
            placeholder: "Choose tags...",
            minimumInputLength: 2,
            debug: true,
            ajax: {
                url: "{{ route('select_specialization') }}",
                dataType: 'json',
                data: function(params) {
                    return {
                        term: params.term || '',
                        page: params.page || 1
                    }
                },
                cache: true,
            }
        });

        $('#job_locations').select2({
            placeholder: "Choose tags...",
            minimumInputLength: 2,
            debug: true,
            ajax: {
                url: "{{ route('select_region') }}",
                dataType: 'json',
                data: function(params) {
                    return {
                        term: params.term || '',
                        page: params.page || 1
                    }
                },
                // processResults: function(data, params) {
                //     params.page = params.page || 1;
                //     return {
                //         results: data.results,
                //         pagination: {
                //             more: (params.page * 10) < data.count_filtered
                //         }
                //     };
                // },
                cache: true,
            }
        });

        //PreSelected Select2
        if (typeof laravel.specialization_sub_id !== undefined) {
            laravel.specialization_sub_id.forEach(data => {
                var newOption = new Option(data.text, data.id, true, true);
                $('#job_specialization').append(newOption).trigger('change');
            });
        }
        if (typeof laravel.region_id !== undefined) {
            laravel.region_id.forEach(data => {
                var newOption = new Option(data.text, data.id, true, true);
                $('#job_locations').append(newOption).trigger('change');
            });
        }
        if (typeof laravel.industries_id !== undefined) {
            laravel.industries_id.forEach(data => {
                var newOption = new Option(data.text, data.id, true, true);
                $('#job_industries').append(newOption).trigger('change');
            });
        }
        if (typeof laravel.categories_id !== undefined) {
            laravel.categories_id.forEach(data => {
                var newOption = new Option(data.text, data.id, true, true);
                $('#job_categories').append(newOption).trigger('change');
            });
        }
        if (typeof laravel.education_id !== undefined) {
            laravel.education_id.forEach(data => {
                var newOption = new Option(data.text, data.id, true, true);
                $('#job_educations').append(newOption).trigger('change');
            });
        }
    });
</script>
@endsection