routes/web.php
<?php
//Controller
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Frontend\SearchController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\Frontend\JobController;
use App\Http\Controllers\GeoLocationController;
use App\Http\Controllers\AuthCompany\AuthCompanyController;
//API
use App\Http\Controllers\API\AuthController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('get-address-from-ip',[GeoLocationController::class, 'index']);

Route::get('/', [HomeController::class, 'index'])->name('index');
Route::get('/reset_password', [HomeController::class, 'resetPassword'] )->name('password.reset');
Route::get('/privacy_policy', [HomeController::class, 'privacyPolicy'] )->name('privacy.policy');
Route::post('/password_update', [HomeController::class, 'passwordUpdate'] )->name('password.update');

Route::get('/search', [SearchController::class, 'index'])->name('search');
Route::get('/job/{id}', [JobController::class, 'index'])->name('job');
Route::get('/login', [AuthCompanyController::class, 'index'] )->name('login');
Route::post('/login', [AuthCompanyController::class, 'login'])->name('login.auth');
Route::post('/logout', [AuthCompanyController::class, 'logout'])->name('logout.auth');

Route::get('/signup', [AuthCompanyController::class, 'viewSignup'] )->name('signup.view');
Route::post('/signup', [AuthCompanyController::class, 'signup'] )->name('signup.auth');

Route::prefix('dashboard')->as('company.')->group(function() {
    Route::get('/',  [DashboardController::class, 'index'] )->name('home');
    Route::get('/applicant/{id}',  [DashboardController::class, 'applicant'] )->name('applicant');
    Route::get('/applicant/selected/{id}',  [DashboardController::class, 'applicantSelected'] )->name('applicant.selected');
    Route::get('/applicant/interviewed/{id}',  [DashboardController::class, 'applicantInterviewed'] )->name('applicant.interviewed');
    Route::get('/applicant/notsuitable/{id}',  [DashboardController::class, 'applicantNotsuitable'] )->name('applicant.notsuitable');
    Route::get('/vacancies/create',  [DashboardController::class, 'vacanciesForm'] )->name('vacancies.form.create');
    Route::get('/companies',  [DashboardController::class, 'companiesForm'] )->name('companies.form.create');
    Route::post('/companies/update',  [DashboardController::class, 'companies'] )->name('companies.update');
    Route::get('/vacancies/update/{id}',  [DashboardController::class, 'vacanciesForm'] )->name('vacancies.form.update');
    Route::post('/vacancies', [DashboardController::class, 'vacancies'])->name('vacancies.create');
    Route::put('/vacancies', [DashboardController::class, 'vacancies'])->name('vacancies.update');

    Route::post('/applicant/update', [DashboardController::class, 'applicantUpdate'])->name('applicant.update');

 });

Route::get('/firebase_auth', function () {
    return view('firebase_auth');
});

Route::get('/firebase_auth_2', function () {
    return view('firebase_auth_2');
});


//For React Only
// Route::get( '/{path?}', function(){
//     return view('index');
// })->where('path', '.*');Auth::routes();

Route::get('/home', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    
    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">
</head>
<body class="bg-gray-100 h-screen antialiased leading-none font-sans">
    <div id="app">
        <header class="bg-blue-900 py-6">
            <div class="container mx-auto flex justify-between items-center px-6">
                <div>
                    <a href="{{ url('/') }}" class="text-lg font-semibold text-gray-100 no-underline">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>
                <nav class="space-x-4 text-gray-300 text-sm sm:text-base">
                    @guest
                        <a class="no-underline hover:underline" href="{{ route('login') }}">{{ __('Login') }}</a>
                        @if (Route::has('register'))
                            <a class="no-underline hover:underline" href="{{ route('register') }}">{{ __('Register') }}</a>
                        @endif
                    @else
                        <span>{{ Auth::user()->name }}</span>

                        <a href="{{ route('logout') }}"
                           class="no-underline hover:underline"
                           onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">{{ __('Logout') }}</a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="hidden">
                            {{ csrf_field() }}
                        </form>
                    @endguest
                </nav>
            </div>
        </header>

        @yield('content')
    </div>
</body>
</html>

resources/views/layouts/auth.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Contact Form Template</title>
    {!! SEOMeta::generate() !!}
    {!! OpenGraph::generate() !!}
    {!! Twitter::generate() !!}
    {!! JsonLd::generate() !!}
    <link href="{{ asset('app/assets/css/style.css') }}" rel="stylesheet">
    <link href="{{ asset('app/assets/library/tailwind/tailwind.min.css') }}" rel="stylesheet">
</head>

<body class>
    <div class="lg:flex">
        <div class="lg:w-1/2 xl:max-w-screen-sm">
            <div class="py-12 bg-blue-100 lg:bg-white flex justify-center lg:justify-start lg:px-12">
                <img class="h-14 mt-3" src="{{ asset('app/images/defaults/akukerja.png') }}"></img>
            </div>
            <div class="mt-10 px-12 sm:px-24 md:px-48 lg:px-12 xl:px-24 xl:max-w-2xl">
                <h2 class="text-center text-4xl text-blue-900 font-display font-semibold lg:text-left xl:text-5xl
                    xl:text-bold">@yield('title')</h2>
                @yield('content')
            </div>
        </div>
        <div class="hidden lg:flex items-center justify-center bg-blue-100 flex-1 h-screen">
            <div class="max-w-xs transform duration-200 hover:scale-110 cursor-pointer">
                @yield('sideimage')
            </div>
        </div>
    </div>
</body>

</html>

resources/views/layouts/backend.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>AkuKerja Dashboard</title>
    <meta name="author" content="name">
    <meta name="description" content="description here">
    <meta name="keywords" content="keywords,here">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <link href="https://unpkg.com/tailwindcss/dist/tailwind.min.css" rel="stylesheet">
    <!--Replace with your tailwind.css once created-->
    <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/@sweetalert2/theme-dark@4/dark.css" rel="stylesheet">
    <!--Totally optional :) -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js" integrity="sha256-xKeoJ50pzbUGkpQxDYHD7o7hxe0LaOGeguUidbq6vis=" crossorigin="anonymous"></script>

</head>


<body class="bg-white shadow-xl font-sans leading-normal tracking-normal mt-8">

    <!--Nav-->
    <nav class="bg-white shadow pt-2 md:pt-1 pb-1 px-1 mt-0 h-auto fixed w-full z-40 top-0">

        <div class="flex flex-wrap items-center">
            <div class="flex flex-shrink md:w-1/3 justify-center md:justify-start text-white">
                <a href="#">
                    <img class="h-10" src="{{ asset('app/images/defaults/akukerja.png') }}"></img>
                </a>
            </div>

            <!-- <div class="flex flex-1 md:w-1/3 justify-center md:justify-start text-white px-2">
                <span class="relative w-full">
                    <input type="search" placeholder="Search" class="w-full bg-gray-900 text-white transition border border-transparent focus:outline-none focus:border-gray-400 rounded py-3 px-2 pl-10 appearance-none leading-normal">
                    <div class="absolute search-icon" style="top: 1rem; left: .8rem;">
                        <svg class="fill-current pointer-events-none text-white w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                            <path d="M12.9 14.32a8 8 0 1 1 1.41-1.41l5.35 5.33-1.42 1.42-5.33-5.34zM8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"></path>
                        </svg>
                    </div>
                </span>
            </div> -->

            <!-- <div class="flex w-full pt-2 content-center justify-between md:w-1/3 md:justify-end">
                <ul class="list-reset flex justify-between flex-1 md:flex-none items-center">
                    <li class="flex-1 md:flex-none md:mr-3">
                        <a class="inline-block py-2 px-4 text-white no-underline" href="#">Active</a>
                    </li>
                    <li class="flex-1 md:flex-none md:mr-3">
                        <a class="inline-block text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4" href="#">link</a>
                    </li>
                    <li class="flex-1 md:flex-none md:mr-3">
                        <div class="relative inline-block">
                            <button onclick="toggleDD('myDropdown')" class="drop-button text-white focus:outline-none"> <span class="pr-2"><i class="em em-robot_face"></i></span> Hi, User <svg class="h-3 fill-current inline" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
                                </svg></button>
                            <div id="myDropdown" class="dropdownlist absolute bg-white shadow-xl text-white right-0 mt-3 p-3 overflow-auto z-30 invisible">
                                <input type="text" class="drop-search p-2 text-gray-600" placeholder="Search.." id="myInput" onkeyup="filterDD('myDropdown','myInput')">
                                <a href="#" class="p-2 hover:bg-white shadow-xl text-white text-sm no-underline hover:no-underline block"><i class="fa fa-user fa-fw"></i> Profile</a>
                                <a href="#" class="p-2 hover:bg-white shadow-xl text-white text-sm no-underline hover:no-underline block"><i class="fa fa-cog fa-fw"></i> Settings</a>
                                <div class="border border-white"></div>
                                <a href="#" class="p-2 hover:bg-white shadow-xl text-white text-sm no-underline hover:no-underline block"><i class="fas fa-sign-out-alt fa-fw"></i> Log Out</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div> -->
        </div>

    </nav>


    <div class="flex flex-col md:flex-row">

        <div class="bg-white shadow-xl h-16 fixed bottom-0 mt-8 md:relative md:h-screen z-10 w-full md:w-48">

            <div class="md:mt-8 md:w-48 md:fixed md:left-0 md:top-0 content-center md:content-start text-left justify-between">
                <ul class="md:mt-5 list-reset flex flex-row md:flex-col py-0 md:py-3 px-1 md:px-2 text-center md:text-left">
                    <li class="mr-3 flex-1">
                        <a href="{{ route('company.home') }}" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-white hover:border-pink-500">
                            <i class="fas fa-home pr-0 md:pr-3" style="color: lightgray;"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-gray-600 md:text-gray-400 block md:inline-block">Dashboard</span>
                        </a>
                    </li>
                    <li class="mr-3 flex-1">
                        <a href="{{ route('company.companies.form.create') }}" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-white hover:border-purple-500">
                            <i class="fa fa-industry pr-0 md:pr-3" style="color: lightgray;"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-gray-600 md:text-gray-400 block md:inline-block">Company</span>
                        </a>
                    </li>
                    <li class="mr-3 flex-1">
                        <a href="{{ route('company.vacancies.form.create') }}" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-white hover:border-green-500">
                            <i class="fa fa-plus pr-0 md:pr-3" style="color: lightgray;"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-gray-600 md:text-gray-400 block md:inline-block">Add Vacancies</span>
                        </a>
                    </li>
                    <li class="mr-3 flex-1">
                        <a href="{{ route('logout.auth') }}" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-white hover:border-yellow-500" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            <i class="fas fa-sign-out-alt fa-fw pr-0 md:pr-3" style="color: lightgray;"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-gray-600 md:text-gray-400 block md:inline-block">Log out</span>
                            <form id="logout-form" action="{{ route('logout.auth') }}" method="POST" class="hidden">
                                {{ csrf_field() }}
                            </form>
                        </a>
                    </li>
                    <!-- <li class="mr-3 flex-1">
                        <a href="#" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-blue-600">
                            <i class="fas fa-chart-area pr-0 md:pr-3 text-blue-600"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-white md:text-white block md:inline-block">Analytics</span>
                        </a>
                    </li>
                    <li class="mr-3 flex-1">
                        <a href="#" class="block py-1 md:py-3 pl-0 md:pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-white hover:border-red-500">
                            <i class="fa fa-wallet pr-0 md:pr-3"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-gray-600 md:text-gray-400 block md:inline-block">Payments</span>
                        </a>
                    </li> -->
                </ul>
            </div>
        </div>
        <div class="main-content flex-1 bg-gray-100 mt-8 md:mt-2 pb-24 md:pb-5">

            <div class="bg-white pt-3">
                <div class="rounded-tl-3xl bg-gray-100 text-2xl text-white h-10">

                </div>
            </div>

            <div class="flex flex-wrap justify-center">
                @yield('content')
            </div>

        </div>
    </div>
    @include ('layouts.js')
    <script>
        /*Toggle dropdown list*/
        function toggleDD(myDropMenu) {
            document.getElementById(myDropMenu).classList.toggle("invisible");
        }
        /*Filter dropdown options*/
        function filterDD(myDropMenu, myDropMenuSearch) {
            var input, filter, ul, li, a, i;
            input = document.getElementById(myDropMenuSearch);
            filter = input.value.toUpperCase();
            div = document.getElementById(myDropMenu);
            a = div.getElementsByTagName("a");
            for (i = 0; i < a.length; i++) {
                if (a[i].innerHTML.toUpperCase().indexOf(filter) > -1) {
                    a[i].style.display = "";
                } else {
                    a[i].style.display = "none";
                }
            }
        }
        // Close the dropdown menu if the user clicks outside of it
        window.onclick = function(event) {
            if (!event.target.matches('.drop-button') && !event.target.matches('.drop-search')) {
                var dropdowns = document.getElementsByClassName("dropdownlist");
                for (var i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (!openDropdown.classList.contains('invisible')) {
                        openDropdown.classList.add('invisible');
                    }
                }
            }
        }
    </script>


</body>

</html>

<script src="{{ asset('app/assets/library/jquery/jquery.min.js') }}"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/27.0.0/classic/ckeditor.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    //Show and hide hamburguer menu in small screens 
    const menu = document.getElementById("menu");
    const ulMenu = document.getElementById("ulMenu");

    function menuToggle() {
        menu.classList.toggle('h-32')
    }

    // Browser resize listener
    window.addEventListener("resize", menuResize);

    // Rezise menu if user changing the width with responsive menu opened
    function menuResize() {
        // first get the size from the window
        const window_size = window.innerWidth || document.body.clientWidth;
        if (window_size > 640) {
            menu.classList.remove('h-32');
        }
    }
</script>
@yield('scripts')

</html>

resources/views/layouts/home.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{ asset('app/assets/library/tailwind/tailwind.min.css') }}" rel="stylesheet">
    <link href="{{ asset('app/assets/css/style.css') }}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ asset('app/assets/library/slick/slick.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('app/assets/library/slick/slick-theme.css') }}" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link href="{{ asset('app/assets/css/select2.custom.css') }}" rel="stylesheet" />
    <link rel="shortcut icon" type="image/ico" href="{{ asset('app/images/defaults/akukerjaicon.ico') }}" />
    {!! SEOMeta::generate() !!}
    {!! OpenGraph::generate() !!}
    {!! Twitter::generate() !!}
    {!! JsonLd::generate() !!}
</head>

<body id="body" class="w-full overflow-x-hidden">
    <div class="w-full relative">
        <div class="w-full h-16 bg-white shadow-lg flex px-5">
            <a href="{{ route('index') }}">
                <img class="h-10 mt-3" src="{{ asset('app/images/defaults/akukerja.png') }}"></img>
            </a>
        </div>
    </div>
    @yield('content')
    <footer class="footer bg-white relative pt-1 border-b-2 border-blue-700">
        <div class="container mx-auto px-6">

            <div class="sm:flex sm:mt-8">
                <div class="mt-8 sm:mt-0 sm:w-full sm:px-8 flex flex-col md:flex-row justify-between">
                    <!-- <div class="flex flex-col">
                        <span class="font-bold text-gray-700 uppercase mb-2">Footer header 1</span>
                        <span class="my-2"><a href="#" class="text-blue-700  text-md hover:text-blue-500">link 1</a></span>
                        <span class="my-2"><a href="#" class="text-blue-700  text-md hover:text-blue-500">link 1</a></span>
                        <span class="my-2"><a href="#" class="text-blue-700  text-md hover:text-blue-500">link 1</a></span>
                    </div>
                    <div class="flex flex-col">
                        <span class="font-bold text-gray-700 uppercase mt-4 md:mt-0 mb-2">Footer header 2</span>
                        <span class="my-2"><a href="#" class="text-blue-700 text-md hover:text-blue-500">link 1</a></span>
                        <span class="my-2"><a href="#" class="text-blue-700  text-md hover:text-blue-500">link 1</a></span>
                        <span class="my-2"><a href="#" class="text-blue-700 text-md hover:text-blue-500">link 1</a></span>
                    </div>
                    <div class="flex flex-col">
                        <span class="font-bold text-gray-700 uppercase mt-4 md:mt-0 mb-2">Footer header 3</span>
                        <span class="my-2"><a href="#" class="text-blue-700  text-md hover:text-blue-500">link 1</a></span>
                        <span class="my-2"><a href="#" class="text-blue-700  text-md hover:text-blue-500">link 1</a></span>
                        <span class="my-2"><a href="#" class="text-blue-700  text-md hover:text-blue-500">link 1</a></span>
                    </div> -->
                </div>
            </div>
        </div>
        <div class="container mx-auto px-6">
            <div class="mt-16 border-t-2 border-gray-300 flex flex-col items-center">
                <div class="sm:w-2/3 text-center py-6">
                    <p class="text-sm text-blue-700 font-bold mb-2">
                        © 2021 AkuKerja
                    </p>
                </div>
            </div>
        </div>
    </footer>
</body>
<script src="{{ asset('app/assets/library/jquery/jquery.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('app/assets/library/slick/slick.min.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="{{ asset('app/assets/js/issue-select2.js') }}"></script>
@include ('layouts.js')
@yield('scripts')

</html>